server:
  port: 8082
spring:
  datasource:
    jdbc-url: jdbc:h2:mem:connexion2_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=false
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
  main:
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

# Application configurations (just for test purpose)
app:
  security:
    jwt:
      secret: 0A7A690F19001C887DEB108AE40C54717E740385243437A863569C91BF8AC99B
      expiration: 86400000